# Generated by Django 6.0.4 on 2026-04-28 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre provisional', max_length=100)),
                ('ciudad', models.CharField(default='Ciudad desconocida', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Jugador Anónimo', max_length=100)),
                ('posicion', models.CharField(default='Sin posición', max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField(default=0, verbose_name='PJ')),
                ('goles', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('asistencias', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0, verbose_name='TA')),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0, verbose_name='TR')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='Estadisticas.jugador')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField(default=2026, verbose_name='Año')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos', to='Estadisticas.equipo')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
    ]
