# Generated by Django 5.2 on 2026-04-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(help_text='Anio en que se obtuvo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('posicion', models.CharField(max_length=50)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='Estadisticas.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='trofeos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='Estadisticas.trofeo'),
        ),
    ]
